name=Maxstick
version=1.0.0
author=Maxo
maintainer=Maxo
sentence=Simple joystick library for Arduino and ESP boards.
paragraph=Easily read X, Y, and switch states from analog joysticks with deadzone and direction detection.
category=Input
url=https://example.com
architectures=*
